[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 90, lines = 24 }
padding.x = 8
padding.y = 26

decorations = "Transparent"
opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13
